---EMPRESA PARA INTEGRAÇÕES E CRUD
INSERT INTO TBR_CAD_COMPANY (IDT_COMPANY,IDT_CORPORATE_GROUP,COD_COMPANY,DSC_COMPANY,D_LAST_UPDATE_DATE,S_LAST_UPDATE_BY,D_CREATION_DATE,S_CREATED_BY,NUM_FED_TAX) 
VALUES ('575',NULL,'800','AUTOMACAO ECF',NULL,NULL,NULL,NULL,'55231342000104');
COMMIT;

---EMPRESA PARA TESTES DE CALCULO LUCRO REAL
INSERT INTO TBR_CAD_COMPANY (IDT_COMPANY,IDT_CORPORATE_GROUP,COD_COMPANY,DSC_COMPANY,D_LAST_UPDATE_DATE,S_LAST_UPDATE_BY,D_CREATION_DATE,S_CREATED_BY,NUM_FED_TAX) 
VALUES ('576',NULL,'801','AUTOMACAO ECF LR',NULL,NULL,NULL,NULL,'66147995000126');
COMMIT;


---EMPRESA PARA TESTES DE CALCULO LUCRO PRESUMIDO
INSERT INTO TBR_CAD_COMPANY (IDT_COMPANY,IDT_CORPORATE_GROUP,COD_COMPANY,DSC_COMPANY,D_LAST_UPDATE_DATE,S_LAST_UPDATE_BY,D_CREATION_DATE,S_CREATED_BY,NUM_FED_TAX) 
VALUES ('577',NULL,'802','AUTOMACAO ECF LP',NULL,NULL,NULL,NULL,'97558106000147');
COMMIT;

---EMPRESA PARA TESTES DE CALCULO LUCRO ESTIMADO
INSERT INTO TBR_CAD_COMPANY (IDT_COMPANY,IDT_CORPORATE_GROUP,COD_COMPANY,DSC_COMPANY,D_LAST_UPDATE_DATE,S_LAST_UPDATE_BY,D_CREATION_DATE,S_CREATED_BY,NUM_FED_TAX) 
VALUES ('578',NULL,'803','AUTOMACAO ECF LE',NULL,NULL,NULL,NULL,'89666708000190');
COMMIT;

---EMPRESA PARA TESTES DE CALCULO LUCRO ARBITRADO
INSERT INTO TBR_CAD_COMPANY (IDT_COMPANY,IDT_CORPORATE_GROUP,COD_COMPANY,DSC_COMPANY,D_LAST_UPDATE_DATE,S_LAST_UPDATE_BY,D_CREATION_DATE,S_CREATED_BY,NUM_FED_TAX) 
VALUES ('579',NULL,'804','AUTOMACAO ECF LA',NULL,NULL,NULL,NULL,'61300665000105');
COMMIT;